title: OBP2
description: Studies on xDSL Dynamics

github_username: plug-obp
rss: rss
google_analytics: UA-127726118-1
show_downloads: false

theme: minima

baseurl: ""
url: "http://plug-obp.github.io"

markdown: kramdown
permalink: pretty
highligher: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
 - jekyll-feed
 - jekyll-seo-tag